CREATE TABLE [dbo].[CUSTOMERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_NAME] [varchar](50) NULL,
	[PASSWORD] [varchar](50) NULL,
	[NAME_SURNAME] [varchar](100) NULL,
	[CUSTOMER_PROFESSION] [varchar](50) NULL,
	[GENDER] [varchar](1) NULL,
	[BIRTHDATE] [date] NULL,
	[CREATEDDATE] [datetime] NULL,
 CONSTRAINT [PK_CUSTOMERS] PRIMARY KEY(ID)
 )

 CREATE TABLE [dbo].[USERWALLET](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [int] NULL,
	[WALLET] [int] NULL,
 CONSTRAINT [PK_USERWALLET] PRIMARY KEY(ID)
 )

CREATE TABLE [dbo].[ITEMS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ITEM_CODE] [varchar](50) NULL,
	[ITEM_NAME] [varchar](100) NULL,
	[UNIT_PRICE] [float] NULL,
	[CATEGORY_1] [varchar](50) NULL,
	[CATEGORY_2] [varchar](50) NULL,
	[CATEGORY_3] [varchar](50) NULL,
	[CATEGORY_4] [varchar](50) NULL,
	[BRAND] [varchar](50) NULL,
 CONSTRAINT [PK_ITEMS] PRIMARY KEY(ID)
)

CREATE TABLE [dbo].[ORDERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [int] NULL,
	[DATE_TIME] [datetime] NULL,
	[TOTAL_PRICE] [decimal](18, 4) NULL,
	[WALLET_ID] [int] NULL,
	[STATUS] [tinyint] NULL,
	[ADDRESS_ID] [int] NULL,
 CONSTRAINT [PK_ORDERS] PRIMARY KEY(ID)
 )


CREATE TABLE [dbo].[ORDER_DETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ORDER_ID] [int] NULL,
	[ITEM_ID] [int] NULL,
	[AMOUNT] [int] NULL,
	[UNIT_PRICE] [decimal](18, 4) NULL,
	[LINE_TOTAL] [decimal](18, 4) NULL,
 CONSTRAINT [PK_ORDER_DETAILS] PRIMARY KEY(ID)
 )


CREATE TABLE [dbo].[ADDRESS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NULL,
	[COUNTRY_ID] [tinyint] NULL,
	[CITY_ID] [smallint] NULL,
	[TOWN_ID] [int] NULL,
	[DISTRICT_ID] [int] NULL,
	[ADDRESSTEXT] [varchar](500) NULL,
	[POSTAL_CODE] [varchar](10) NULL,
 CONSTRAINT [PK_ADDRESS] PRIMARY KEY(ID)
)


 CREATE TABLE [dbo].[COUNTRIES](
	[ID] [tinyint] IDENTITY(1,1) NOT NULL,
	[COUNTRY] [varchar](50) NULL,
 CONSTRAINT [PK_COUNTRIES] PRIMARY KEY(ID)
 )


CREATE TABLE [dbo].[CITIES](
	[ID] [smallint] IDENTITY(1,1) NOT NULL,
	[COUNTRY_ID] [tinyint] NULL,
	[CITY] [varchar](50) NULL,
 CONSTRAINT [PK_CITIES] PRIMARY KEY(ID)
 )


 CREATE TABLE [dbo].[DISTRICTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TOWN_ID] [int] NULL,
	[DISTRICT] [varchar](50) NULL,
 CONSTRAINT [PK_DISTRICTS] PRIMARY KEY(ID)
 )
